export const subjectTopics = {
  subjects: [
    "Physics",
    "Maths",
    "Chemistry",
    "Botany",
    "Zoology",
    "General/Financial-Awareness",
    "Reasoning & Computer Aptitude",
    "English Language",
    "Reasoning Ability",
    "Numerical Ability",
    "Quantitative Aptitude",
    "General/Economy/Banking Awareness",
    "Computer Awareness",
    "GK/IQ",
    "General Knowledge",
    "GK/Banking/Account/Math",
    "Management",
    "Account",
    "Economics",
    "Banking"
  ],
  topics: [
    [
      "Introduction to Physics",
      "Heat and Temperature",
      "Concepts of Physics and Mathematics",
      "Kinetic Theory of Gases",
      "Rest and Motion: Kinematics",
      "Calorimetry",
      "Forces",
      "Law of Thermodynamics",
      "Newton’s Laws of Motion",
      "Specific heat Capacities of gases",
      "Friction",
      "Heat Transfer",
      "Circular Motion",
      "Electric Field and Potential",
      "Work and Energy",
      "Gauss's Law",
      "Centre of Mass, Linear Momentum, Collision",
      "Capacitors",
      "Rotational Mechanics",
      "Electric current in conductors",
      "Gravitation",
      "Thermal and chemical effects of electric current",
      "Simple Harmonic Motion",
      "Magnetic field",
      "Fluid Mechanics",
      "Magnetic field due to a current",
      "Some Mechanical Properties of Matter",
      "Permanent Magnets",
      "Wave Motion and Waves on a String",
      "Magnetic properties of matter",
      "Sound Waves",
      "Electromagnetic Induction",
      "Light Waves",
      "Alternating current",
      "Geometrical Optics",
      "Electromagnetic Waves",
      "Optical Instruments",
      "Electric Current through gases",
      "Dispersion and Spectra",
      "Photoelectric Effect and wave- Particle Duality",
      "Speed of Light",
      "Bohr's Model and Physics of the Atom",
      "Photometry",
      "X-rays",
      "Semiconductors and Semiconductor Devices",
      "The Nucleus",
      "The special theory of relativity",
      "Unit and Dimensions",
      "Error in Measurement",
      "Rectilinear Motion",
      "Projectile Motion",
      "Relative Motion",
      "Elasticity",
      "Viscosity",
      "Surface Tension",
      "Modern Physics",
      "Nuclear Physics",
      "Principles of Communication"
    ],
    [
      "Sets, relations and functions",
      "Complex numbers",
      "Quadratic equations",
      "Matrices and determinants",
      "Permutations and combinations",
      "Mathematical induction",
      "Binomial theorem",
      "Sequences and series",
      "Limit, continuity and differentiability",
      "Differential equations",
      "Integral calculus",
      "Coordinate Geometry",
      "Three dimensional geometry",
      "Vector algebra",
      "Statistics and probability",
      "Trigonometry",
      "Mathematical reasoning"
    ],
    [
      "Some Basic Concepts in Chemistry",
      "States of Matter",
      "Atomic Structure",
      "Chemical Bonding and Molecular Structure",
      "Chemical Thermodynamics",
      "Solutions",
      "Equilibrium",
      "Redox Reactions and Electrochemistry",
      "Chemical Kinetics",
      "Surface Chemistry",
      "Classification of Elements and Periodicity in Properties",
      "Metallurgy",
      "Hydrogen",
      "s-Block Elements (Alkali and Alkaline Earth Metals)",
      "p-Block Elements",
      "d and f Block Elements",
      "Co-Ordination Compounds",
      "Environmental Chemistry",
      "Qualitative Analysis",
      "Fundamental Concept in Organic and Reaction Mechanism",
      "Hydrocarbons",
      "Alkyl Halides",
      "Alcohol, Phenol, Ether",
      "Nitrogen Containing Compounds",
      "Polymers",
      "Biomolecules",
      "Chemistry In Everyday Life",
      "Principles Related to Practical Chemistry",
      "Aldehydes",
      "Ketones",
      "Carboxylic Acid Derivatives",
      "Isomerism and Separation Techniques"
    ],
    [
      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Reproduction in Organisms",
      "Sexual Reproduction in Flowering Plants",
      "Principles of Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Strategies for Enhancement in Food Production",
      "Biotechnology : Principles and Processes",
      "Biotechnology and its Applications",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and Conservation",
      "Environmental Issues"
    ],
    [
      "Animal Kingdom",
      "Structural Organisation in Animals",
      "Cell : The Unit of Life",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Digestion and Absorption",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration",
      "Human Reproduction",
      "Reproductive Health",
      "Evolution",
      "Human Health and Disease",
      "Microbes in Human Welfare",
      "Strategies for Enhancement in Food Production"
    ],
    ["Financial Awareness", "Current Affairs", "General Knowledge"],
    [
      "Verbal Reasoning",
      "Syllogism",
      "Circular Seating Arrangement",
      "Linear Seating Arrangement",
      "Double Lineup",
      "Scheduling",
      "Input-Output",
      "Blood Relations",
      "Directions and Distances",
      "Ordering and Ranking",
      "Data Sufficiency",
      "Coding and Decoding",
      "Code Inequalities",
      "Internet",
      "Memory",
      "Keyboard Shortcuts",
      "Computer Abbreviation",
      "Microsoft Office",
      "Computer Hardware",
      "Computer Software",
      "Operating System",
      "Networking",
      "ComputerFundamentals/Terminologies"
    ],
    [
      "Reading Comprehension",
      "Vocabulary",
      "Grammar",
      "Verbal Ability",
      "Reading Comprehension",
      "Cloze Test",
      "Para jumbles",
      "Multiple Meaning/Error Spotting",
      "Fill in the blanks",
      "Miscellaneous",
      "Paragraph Completion"
    ],
    [
      "Logical Reasoning",
      "Alphanumeric Series",
      "Ranking",
      "Direction",
      "Alphabet Test",
      "Data Sufficiency",
      "Coded Inequalities",
      "Seating Arrangement",
      "Puzzle",
      "Tabulation",
      "Syllogism",
      "Blood Relations",
      "Input-Output",
      "Coding-Decoding"
    ],
    [
      "Simplification",
      "Average",
      "Profit&Loss",
      "Mixtures & Alligations",
      "Simple Interest&Compound Interest",
      "Surds & Indices",
      "Work&Time",
      "Time&Distance",
      "Mensuration-Cylinder,Cone,Sphere",
      "Data Interpretation",
      "Ratio&Proportion",
      "Percentage",
      "Number Systems",
      "Sequence&Series",
      "Permutation&Combination",
      "Probability",
      "Problems of Ages",
      "Mensuration and Geometry",
      "Quadratic Equation",
      "Speed,Distance and Time",
      "Data Sufficiency",
      "Linear Equation"
    ],
    [
      "Simplification",
      "Average",
      "Profit&Loss",
      "Mixtures & Alligations",
      "Simple Interest&Compound Interest",
      "Surds & Indices",
      "Work & Time",
      "Time & Distance",
      "Mensuration-Cylinder,Cone,Sphere",
      "Data Interpretation",
      "Ratio&Proportion",
      "Percentage",
      "Number Systems",
      "Sequence&Series",
      "Permutation&Combination",
      "Probability",
      "Problems of Ages",
      "Mensuration and Geometry",
      "Quadratic Equation",
      "Speed,Distance and Time",
      "Data Sufficiency",
      "Linear Equation"
    ],
    [
      "Financial Awareness",
      "Current Affairs",
      "General Knowledge",
      "Static Awareness",
      "Banking and Financial Awareness"
    ],
    [
      "Internet",
      "Memory",
      "Keyboard Shortcuts",
      "Computer Abbreviation",
      "Microsoft Office",
      "Computer Hardware",
      "Computer Software",
      "Operating System",
      "Networking",
      "Computer Fundamentals/Terminologies"
    ],
    [],
    [],
    [],
    [],
    [],
    [],
    []
  ]
}
